import Vue from 'vue'
import { Icon } from 'vant';
import { Popover } from 'vant';
import { Toast } from 'vant';
import { PullRefresh } from 'vant';
import { Empty } from 'vant';
import { Tab, Tabs } from 'vant';
import { Popup } from 'vant';
import { Divider } from 'vant';
import { Form } from 'vant';
import { Field } from 'vant';
import { Uploader } from 'vant';
import { Loading } from 'vant';
import { Button } from 'vant';
import { RadioGroup, Radio } from 'vant';
import { DatetimePicker } from 'vant';
import { Image as VanImage } from 'vant';
import { Lazyload } from 'vant';
import { Tag } from 'vant';

Vue.use(Tag);
Vue.use(Lazyload);
Vue.use(VanImage);
Vue.use(DatetimePicker);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Button);
Vue.use(Loading);
Vue.use(Uploader);
Vue.use(Form);
Vue.use(Field);
Vue.use(Divider);
Vue.use(Popup);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Empty);
Vue.use(PullRefresh);
Vue.use(Toast);
Vue.use(Popover);
Vue.use(Icon);